version: "3.1"
# 服务配置
services:
  kibana:
    image: kibana:8.6.0
    container_name: kibana
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
      - "I18N_LOCALE=zh-CN"
    ports:
      - "5601:5601"
    volumes:
    - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:rw