version: '3'

services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbit
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./data:/var/lib/rabbitmq:rw
      - ./conf:/etc/rabbitmq:rw