version: '3'
services:
  mysql-test:
    image: mysql:8.0.13
    restart: always
    container_name: mysql
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci